- id: '1744814535238'
  alias: Update ISPRA Sensor
  description: ''
  triggers:
  - minutes: '0'
    trigger: time_pattern
  - trigger: state
    entity_id:
    - input_button.ispra_update
    to:
  actions:
  - action: shell_command.download_ispra_c6h6_data
    data: {}
  - action: shell_command.download_ispra_pm25_data
    data: {}
  - action: shell_command.download_ispra_pm10_data
    data: {}
  - action: shell_command.download_ispra_o3_data
    data: {}
  - action: shell_command.download_ispra_so2_data
    data: {}
  - action: shell_command.download_ispra_no2_data
    data: {}
  - action: shell_command.download_ispra_co_data
    data: {}
  - delay: 00:00:10
  - target:
      entity_id: sensor.co_orario_it1658a
    action: homeassistant.update_entity
    data:
      entity_id:
      - sensor.co_ispra
      - sensor.o3_ispra
      - sensor.c6h6_ispra
      - sensor.no2_ispra
      - sensor.pm10_ispra
      - sensor.so2_ispra
      - sensor.pm25_ispra
