homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Indice Qualità Ambientale'
        author: 'Ippolito Salati - Kapkirk'
        reference: 'WebSite: https://github.com/kapkirk/'

####################################################
#                                                  #
#              IMPOSTAZIONI PACKAGE                #
#                                                  #
####################################################

      setting: # Node anchors per i comandi curl (DEVONO essere al livello root)
        stringa_co: &stringa_co 'curl -s -L -o /config/dati_ispra/co_data.csv "https://sdi.isprambiente.it/geoserver/infoaria/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=infoaria%3Adati_nrt_informambiente_mv&CQL_FILTER=region_name=%27PUGLIA%27+AND+pollutant_id=%2710%27&maxFeatures=10000&outputFormat=csv"'
        stringa_so2: &stringa_so2 'curl -s -L -o /config/dati_ispra/so2_data.csv "https://sdi.isprambiente.it/geoserver/infoaria/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=infoaria%3Adati_nrt_informambiente_mv&CQL_FILTER=region_name=%27PUGLIA%27+AND+pollutant_id=%271%27&maxFeatures=10000&outputFormat=csv"'
        stringa_c6h6: &stringa_c6h6 'curl -s -L -o /config/dati_ispra/c6h6_data.csv "https://sdi.isprambiente.it/geoserver/infoaria/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=infoaria%3Adati_nrt_informambiente_mv&CQL_FILTER=region_name=%27PUGLIA%27+AND+pollutant_id=%2720%27&maxFeatures=10000&outputFormat=csv"'
        stringa_pm10: &stringa_pm10 'curl -s -L -o /config/dati_ispra/pm10_data.csv "https://sdi.isprambiente.it/geoserver/infoaria/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=infoaria%3Adati_nrt_informambiente_mv&CQL_FILTER=region_name=%27PUGLIA%27+AND+pollutant_id=%275%27&maxFeatures=10000&outputFormat=csv"'
        stringa_pm25: &stringa_pm25 'curl -s -L -o /config/dati_ispra/pm25_data.csv "https://sdi.isprambiente.it/geoserver/infoaria/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=infoaria%3Adati_nrt_informambiente_mv&CQL_FILTER=region_name=%27PUGLIA%27+AND+pollutant_id=%276001%27&maxFeatures=10000&outputFormat=csv"'
        stringa_o3: &stringa_o3 'curl -s -L -o /config/dati_ispra/o3_data.csv "https://sdi.isprambiente.it/geoserver/infoaria/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=infoaria%3Adati_nrt_informambiente_mv&CQL_FILTER=region_name=%27PUGLIA%27+AND+pollutant_id=%277%27&maxFeatures=10000&outputFormat=csv"'
        stringa_no2: &stringa_no2 'curl -s -L -o /config/dati_ispra/no2_data.csv "https://sdi.isprambiente.it/geoserver/infoaria/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=infoaria%3Adati_nrt_informambiente_mv&CQL_FILTER=region_name=%27PUGLIA%27+AND+pollutant_id=%278%27&maxFeatures=10000&outputFormat=csv"'

####################################################
#                                                  #
#                   SENSORI                        #
#                                                  #
####################################################

shell_command:
  download_ispra_co_data: *stringa_co
  download_ispra_so2_data: *stringa_so2
  download_ispra_c6h6_data: *stringa_c6h6
  download_ispra_pm10_data: *stringa_pm10
  download_ispra_pm25_data: *stringa_pm25
  download_ispra_o3_data: *stringa_o3
  download_ispra_no2_data: *stringa_no2

command_line:
  - sensor:
      name: "co_ispra"
      unique_id: "co_ispra"
      command: 'python3 /config/python_scripts/ispra.py'
      value_template: '{{ value_json.CO.value }}'
      state_class: measurement
      json_attributes_path: "$.CO"
      json_attributes:
        - full_data
      scan_interval: 3600

  - sensor:
      name: "so2_ispra"
      unique_id: "so2_ispra"
      command: 'python3 /config/python_scripts/ispra.py'
      value_template: '{{ value_json.SO2.value }}'
      state_class: measurement
      json_attributes_path: "$.SO2"
      json_attributes:
        - full_data
      scan_interval: 3600

  - sensor:
      name: "c6h6_ispra"
      unique_id: "c6h6_ispra"
      command: 'python3 /config/python_scripts/ispra.py'
      value_template: '{{ value_json.C6H6.value }}'
      state_class: measurement
      json_attributes_path: "$.C6H6"
      json_attributes:
        - full_data
      scan_interval: 3600

  - sensor:
      name: "pm10_ispra"
      unique_id: "pm10_ispra"
      command: 'python3 /config/python_scripts/ispra.py'
      value_template: '{{ value_json.PM10.value }}'
      state_class: measurement
      json_attributes_path: "$.PM10"
      json_attributes:
        - full_data
      scan_interval: 3600

  - sensor:
      name: "pm25_ispra"
      unique_id: "pm25_ispra"
      command: 'python3 /config/python_scripts/ispra.py'
      value_template: '{{ value_json.PM25.value }}'
      state_class: measurement
      json_attributes_path: "$.PM25"
      json_attributes:
        - full_data
      scan_interval: 3600

  - sensor:
      name: "o3_ispra"
      unique_id: "o3_ispra"
      command: 'python3 /config/python_scripts/ispra.py'
      value_template: '{{ value_json.O3.value }}'
      state_class: measurement
      json_attributes_path: "$.O3"
      json_attributes:
        - full_data
      scan_interval: 3600

  - sensor:
      name: "no2_ispra"
      unique_id: "no2_ispra"
      command: 'python3 /config/python_scripts/ispra.py'
      value_template: '{{ value_json.NO2.value }}'
      state_class: measurement
      json_attributes_path: "$.NO2"
      json_attributes:
        - full_data
      scan_interval: 3600

####################################################
#                                                  #
#               TEMPLATE                           #
#                                                  #
####################################################

sensor:
  - platform: template
    sensors:
      aqi_ispra:
        friendly_name: qualita_aria_ispra
        value_template: >
          {% set pm10 = state_attr('sensor.pm10_ispra', 'full_data') %}
          {% set pm25 = state_attr('sensor.pm25_ispra', 'full_data') %}
          {% set co = state_attr('sensor.co_ispra', 'full_data') %}
          {% set c6h6 = state_attr('sensor.c6h6_ispra', 'full_data') %}
          {% set no2 = state_attr('sensor.no2_ispra', 'full_data') %}
          {% set so2 = state_attr('sensor.so2_ispra', 'full_data') %}
          {% set o3 = state_attr('sensor.o3_ispra', 'full_data') %}

          {% set valori_numerici = [] %}
          {% if pm10 and pm10.pollutant_level and pm10.pollutant_level|int > 0 %} {% set valori_numerici = valori_numerici + [pm10.pollutant_level|int] %} {% endif %}
          {% if pm25 and pm25.pollutant_level and pm25.pollutant_level|int > 0 %} {% set valori_numerici = valori_numerici + [pm25.pollutant_level|int] %} {% endif %}
          {% if co and co.pollutant_level and co.pollutant_level|int > 0 %} {% set valori_numerici = valori_numerici + [co.pollutant_level|int] %} {% endif %}
          {% if c6h6 and c6h6.pollutant_level and c6h6.pollutant_level|int > 0 %} {% set valori_numerici = valori_numerici + [c6h6.pollutant_level|int] %} {% endif %}
          {% if no2 and no2.pollutant_level and no2.pollutant_level|int > 0 %} {% set valori_numerici = valori_numerici + [no2.pollutant_level|int] %} {% endif %}
          {% if so2 and so2.pollutant_level and so2.pollutant_level|int > 0 %} {% set valori_numerici = valori_numerici + [so2.pollutant_level|int] %} {% endif %}
          {% if o3 and o3.pollutant_level and o3.pollutant_level|int > 0 %} {% set valori_numerici = valori_numerici + [o3.pollutant_level|int] %} {% endif %}

          {% if valori_numerici %}
            {% set valore_peggiore = valori_numerici | min %}
            {% set classi = {
              '6': 'ottima',
              '5': 'buona',
              '4': 'discreta',
              '3': 'sufficiente',
              '2': 'scarsa',
              "1": 'pessima'
            } %}
            {{ classi[valore_peggiore | string] if valore_peggiore|string in classi else 'non disponibile' }}
          {% else %}
            non disponibile
          {% endif %}

####################################################
#                                                  #
#               BUTTON                             #
#                                                  #
####################################################

input_button:
  ispra_update:
    name: Ispra Update
    icon: mdi:button-cursor

####################################################
#                                                  #
#                     AUTOMAZIONI                  #
#                                                  #
####################################################

automation:
  - alias: "Update ISPRA Sensor"
    description: "Aggiorna i dati ISPRA ogni ora o manualmente"
    trigger:
      - platform: time_pattern
        minutes: "0"
      - platform: state
        entity_id: input_button.ispra_update
    action:
      - service: shell_command.download_ispra_co_data
      - service: shell_command.download_ispra_so2_data
      - service: shell_command.download_ispra_c6h6_data
      - service: shell_command.download_ispra_pm10_data
      - service: shell_command.download_ispra_pm25_data
      - service: shell_command.download_ispra_o3_data
      - service: shell_command.download_ispra_no2_data
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: homeassistant.update_entity
        data:
          entity_id:
            - sensor.co_ispra
            - sensor.so2_ispra
            - sensor.c6h6_ispra
            - sensor.pm10_ispra
            - sensor.pm25_ispra
            - sensor.o3_ispra
            - sensor.no2_ispra
